

name: Close inactive issues
on:
workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *"
jobs:
  close-issues:
    # Don't do this in forks
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Awaiting response issues
        uses: actions/stale@v5
        with:
          days-before-issue-stale: 0
          days-before-issue-close: 0
          stale-issue-label: "stale"
          # reason for closed the issue default value is not_planned
          close-issue-reason: completed
          only-labels: "stat:awaiting response from contributor"
          stale-issue-message: > 
            This issue is stale because it has been open for 7 days with no activity.
            It will be closed if no further activity occurs. Thank you.
          close-issue-message: >
            This issue was closed because it has been inactive for 7 days since being marked as stale.
            Please reopen if you'd like to work on this further.
          days-before-pr-stale: 0
          days-before-pr-close: 0
          stale-pr-message: "This PR is stale because it has been open for 14 days with no activity. It will be closed if no further activity occurs. Thank you."
          close-pr-message: "This PR was closed because it has been inactive for 14 days since being marked as stale. Please reopen if you'd like to work on this further."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Contribution issues
        uses: actions/stale@v5
        with:
          days-before-issue-stale: 0
          days-before-issue-close: 0
          stale-issue-label: "stale"
          # reason for closed the issue default value is not_planned
          close-issue-reason: completed
          any-of-labels: "stat:contributions welcome,stat:good first issue"
          stale-issue-message: > 
            This issue is stale because it has been open for 180 days with no activity.
            It will be closed if no further activity occurs. Thank you.
          close-issue-message: >
            This issue was closed because it has been inactive for 1 year.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
