name: Close inactive issues
on:
  schedule:
    - cron: "*/2 * * * *"
jobs:
  close-issues:
    # Don't do this in forks
    if: github.repository == 'TestGithub'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Awaiting response issues
        uses: actions/stale@v5
        with:
          days-before-issue-stale: 0
          days-before-issue-close: 0
          stale-issue-label: "stale"
          # reason for closed the issue default value is not_planned
          close-issue-reason: completed
          only-labels: "stat:awaiting response from contributor"
          stale-issue-message: > 
            This issue is stale because it has been open for 7 days with no activity.
            It will be closed if no further activity occurs. Thank you.
	@@ -43,17 +44,18 @@ jobs:
            Please reopen if you'd like to work on this further.
          days-before-pr-stale: 14
          days-before-pr-close: 14
          stale-pr-message: "This PR is stale because it has been open for 14 days with no activity. It will be closed if no further activity occurs. Thank you."
          close-pr-message: "This PR was closed because it has been inactive for 14 days since being marked as stale. Please reopen if you'd like to work on this further."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Contribution issues
        uses: actions/stale@v5
        with:
          days-before-issue-stale: 0
          days-before-issue-close: 0
          stale-issue-label: "stale"
          # reason for closed the issue default value is not_planned
          close-issue-reason: not_planned
          any-of-labels: "stat:contributions welcome,stat:good first issue"
          stale-issue-message: > 
            This issue is stale because it has been open for 180 days with no activity.
            It will be closed if no further activity occurs. Thank you.
	
